backend:
  name: git-gateway

media_folder: "site/static/public/images" # Folder where user uploaded files should go
public_folder: "/public/images"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/ai/_index.md"
        label: "Ponddy AI"
        name: ai
        fields:
          - label: Site Settings
            name: site
            widget: object
            fields:
              - label: Title
                name: title 
                widget: string
              - label: Author
                name: author
                widget: string
              - label: Keywords
                name: keywords
                widget: string
              - label: Classification
                name: classification
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Copyright
                name: copyright
                widget: string
              - label: Logo
                name: logo
                widget: object
                fields:
                - label: Image
                  name: image
                  widget: image
                - label: Title
                  name: title
                  widget: string
                - label: Alt
                  name: alt
                  widget: string
          - label: Header – Menu Links
            name: header
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Link-to Section
                name: link_section
                widget: string
          - label: Footer
            name: footer
            widget: object
            fields:
              - label: Products (Logo)
                name: products_icon
                widget: list
                fields:
                  - label: Logo of the Product
                    name: image
                    widget: image
                  - label: Link to the Product Page
                    name: url
                    widget: string
              - label: Box - Our Products
                name: our_products
                widget: object
                fields:
                  - label: Name of the Box
                    name: title
                    widget: string
                  - label: Product entries
                    name: links
                    widget: list
                    fields:
                      - label: Name of the Product
                        name: title
                        widget: string
                      - label: Link to the Product Page
                        name: url
                        widget: string
              - label: Box - Work
                name: work
                widget: object
                fields:
                  - label: Name of the Box
                    name: title
                    widget: string
                  - label: Link entries
                    name: links
                    widget: list
                    fields:
                      - label: Link title
                        name: title
                        widget: string
                      - label: Link URL
                        name: url
                        widget: string
              - label: Box - Resources
                name: resources
                widget: object
                fields:
                  - label: Name of the Box
                    name: title
                    widget: string
                  - label: Resource entries
                    name: links
                    widget: list
                    fields:
                      - label: Link title
                        name: title
                        widget: string
                      - label: Link URL
                        name: url
                        widget: string
              - label: Box - Terms and Policies
                name: tnp
                widget: object
                fields:
                  - label: Name of the Box
                    name: title
                    widget: string
                  - label: Link entries
                    name: links
                    widget: list
                    fields:
                      - label: Link title
                        name: title
                        widget: string
                      - label: Link URL
                        name: url
                        widget: string
              - label: Copyright
                name: copyright
                widget: string
          - label: Main - Site content
            name: main
            widget: object
            fields:
              - label: Website Hero
                name: hero
                widget: object
                fields:
                  - {label: Headline, name: headline, widget: markdown}
                  - {label: Image 1, name: image1, widget: image}
                  - {label: Image 2, name: image2, widget: image}
                  - {label: Image 3, name: image3, widget: image}
              - label: Who We Are
                name: about
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: text, widget: text}
                  - label: Boxes
                    name: boxes
                    widget: list
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: Image
                        name: image
                        widget: image
                      - label: Content
                        name: text
                        widget: text
              - label: AI
                name: ai
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: text, widget: text}
                  - {label: Image, name: image, widget: image}
              - label: Knowledge
                name: knowledge
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: text, widget: text}
              - label: Whate We Do
                name: services
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: text, widget: text}
              - label: Tutors
                name: tutors
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: text}
                  - {label: Link URL, name: url, widget: string}
                  - {label: Button Text, name: button_text, widget: string}
              - label: Reader
                name: reader
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: text}
                  - {label: Link URL, name: url, widget: string}
                  - {label: Button Text, name: button_text, widget: string}
              - label: Textbooks
                name: textbooks
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: text}
                  - {label: Link URL, name: url, widget: string}
                  - {label: Button Text, name: button_text, widget: string}
              - label: News
                name: news
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Arrow - Right, name: arrow_right, widget: image}
                  - {label: Arrow - Left, name: arrow_left, widget: image}
                  - {label: Button Text, name: button_text, widget: string}
                  - label: Carousel
                    name: carousel
                    widget: list
                    fields:
                      - {label: Image, name: image, widget: image}
                      - {label: Content, name: text, widget: text}
                      - {label: Link URL, name: url, widget: string}
              - label: Social Networks
                name: social
                widget: object
                fields:
                  - {label: Facebook, name: facebook, widget: string}
                  - {label: Twitter, name: twitter, widget: string}
                  - {label: Youtube, name: youtube, widget: string}
                  - {label: Instagram, name: instagram, widget: string}
                  - {label: LinkedIn, name: linkedin, widget: string}
